export const animes = [
  "Sousou no Frieren",
  "Fullmetal Alchemist: Brotherhood",
  "Steins;Gate",
  "Attack on Titan",
  "Gintama",
  "Bleach",
  "Hunter x Hunter",
  "One Piece",
  "Naruto",
  "Dragon Ball",
  "Cowboy Bebop",
  "Death Note",
  "Code Geass",
  "Jujutsu Kaisen",
  "Demon Slayer",
  "My Hero Academia",
  "Haikyuu",
  "Spy x Family",
  "Chainsaw Man",
  "Mob Psycho 100",
  "One Punch Man",
  "JoJo's Bizarre Adventure",
  "Neon Genesis Evangelion",
  "Ghost in the Shell",
  "Berserk",
  "Hellsing",
  "Trigun",
  "Serial Experiments Lain",
  "Paranoia Agent",
  "Monster",
  "Ergo Proxy",
  "Psycho-Pass",
  "Tokyo Ghoul",
  "Parasyte",
  "Elfen Lied",
  "Higurashi When They Cry",
  "Mirai Nikki",
  "Another",
  "Deadman Wonderland",
  "Black Lagoon",
  "Jormungand",
  "Durarara",
  "Baccano",
  "No Game No Life",
  "Re:Zero",
  "Konosuba",
  "Overlord",
  "Tensura",
  "Sword Art Online",
  "Log Horizon",
  "Accel World",
  "Aldnoah.Zero",
  "Guilty Crown",
  "Darwin's Game",
  "Kakegurui",
  "Akame ga Kill",
  "The Seven Deadly Sins",
  "Assassination Classroom",
  "Dr. Stone",
  "Fire Force",
  "Black Clover",
  "Fairy Tail",
  "Rave Master",
  "Zatch Bell",
  "Shaman King",
  "Yu Yu Hakusho",
  "Inuyasha",
  "Rurouni Kenshin",
  "Samurai Champloo",
  "Afro Samurai",
  "Basilisk",
  "Gurren Lagann",
  "Kill la Kill",
  "Panty & Stocking with Garterbelt",
  "Nichijou",
  "Danshi koukousei no nichijou",
  "Azumanga Daioh",
  "Lucky Star",
  "K-On!",
  "Love Hina",
  "Love Stage",
  "Tenchi Muyo!",
  "Ranma 1/2",
  "Urusei Yatsura",
  "Maison Ikkoku",
  "Ah! My Goddess",
  "El-Hazard",
  "Slayers",
  "Fushigi Yuugi",
  "Cardcaptor Sakura",
  "Chobits",
  "DearS",
  "Ai Yori Aoshi",
  "Kanon",
  "Air",
  "Clannad",
  "Toradora!",
  "The Familiar of Zero",
  "Shakugan no Shana",
  "School Days",
  "Shuffle!",
  "True Tears",
  "Kimikiss",
  "Amagami SS",
  "Golden Time",
  "White Album 2",
  "Oreimo",
  "Eromanga Sensei",
  "Nisekoi",
  "To Love-Ru",
  "High School DxD",
  "Monster Musume",
  "Date A Live",
  "Infinite Stratos",
  "Strike the Blood",
  "Trinity Seven",
  "Grimgar",
  "Gate",
  "Youjo Senki",
  "Goblin Slayer",
  "Arifureta",
  "Maou Gakuin",
  "Death March",
  "Tate no Yūsha no Nariagari ",
  "The Eminence in Shadow",
  "Tsukimichi: Moonlit Fantasy",
  "Mushoku Tensei",
  "Kumo desu ga, nani ka",
  "The Aristocrat's Otherworldly Adventure",
  "Wise Man's Grandchild",
  "Black Summoner",
  "The Strongest Exorcist",
  "Kono Yuusha",
  "Seiken Gakuin no Maken Tsukai",
  "Farming Life in Another World",
  "By the Grace of the Gods",
  "Outbreak Company",
  "Mondaiji-tachi",
  "Demon Lord, Retry!",
  "Isekai Cheat Magician",
  "The Fruit of Evolution",
  "In the Land of Leadale",
  "Hamehura",
  "Honzuki no gekokujou",
  "Kuma Kuma Kuma Bear",
  "Banished from the Hero's Party",
  "Chivalry of a Failed Knight",
  "Hyakuren no Haō to Seiyaku no Valkyria",
  "Madan no Ou to Vanadis",
  "Seirei no Moribito",
  "Spice and Wolf",
  "Maoyu: Archenemy & Hero",
  "Drifters",
  "Hataraku Maou-sama!",
  "Danmachi",
  ".hack//SIGN",
  "The Twelve Kingdoms",
  "The Big O",
  "Patlabor",
  "Bubblegum Crisis",
  "Appleseed",
  "Akira",
  "Roujin Z",
  "Patlabor: The Movie",
  "Jin-Roh: The Wolf Brigade",
  "Perfect Blue",
  "Millennium Actress",
  "Paprika",
  "Tokyo Godfathers",
  "The Girl Who Leapt Through Time",
  "Summer Wars",
  "Wolf Children",
  "A Silent Voice",
  "Your Name",
  "Tenki no ko",
  "Spirited Away",
  "Princess Mononoke",
  "My Neighbor Totoro",
  "Kiki's Delivery Service",
  "Howl's Moving Castle",
  "Ponyo",
  "Castle in the Sky",
  "Porco Rosso",
  "Only Yesterday",
  "Sailor Moon",
  "Pretty Cure",
  "Ojamajo Doremi",
  "Tokyo Mew Mew",
  "Shugo Chara!",
  "Jewelpet",
  "PriPara",
  "Aikatsu!",
  "Love Live!",
  "BanG Dream!",
  "The Idolmaster",
  "Uta no Prince-sama",
  "Macross",
  "Mobile Suit Gundam",
  "Zeta Gundam",
  "Gundam ZZ",
  "Gundam Wing",
  "Gundam SEED",
  "Gundam 00",
  "Full Metal Panic!",
  "RahXephon",
  "Eureka Seven",
  "Macross Frontier",
  "Aquarion",
  "Heroic Age",
  "Blue Submarine No. 6",
  "Vandread",
  "Legend of the Galactic Heroes",
  "86",
  "Kabaneri of the Iron Fortress",
  "God Eater",
  "Seraph of the End",
  "Ajin: Demi-Human",
  "Kekkai Sensen",
  "Bungo Stray Dogs",
  "Noragami",
  "Blue Exorcist",
  "D.Gray-man",
  "Soul Eater",
  "Dorohedoro",
  "Made in Abyss",
  "Hoseki no Kuni",
  "Violet Evergarden",
  "Your Lie in April",
  "Anohana",
  "Tsuki ga Kirei",
  "Sangatsu no Lion",
  "Barakamon",
  "Non Non Biyori",
  "Laid-Back Camp",
  "Flying Witch",
  "Kyokai no Kanata",
  "Plastic Memories",
  "Angel Beats!",
  "Angels of Death",
  "Charlotte",
  "Sakura-sou no Pet na Kanojo",
  "My Little Monster",
  "Sukitte Ii na yo",
  "Lovely Complex",
  "Kimi ni Todoke",
  "Itazura na Kiss",
  "Skip Beat!",
  "Fruits Basket",
  "Ouran High School Host Club",
  "Special A",
  "Maid Sama!",
  "Kamisama Kiss",
  "Inu x Boku SS",
  "Wolf's Rain",
  "Tenkuu no Shiro Laputa",
  "The Wind Rises",
  "My Neighbor Totoro",
  "Princess Mononoke",
  "Spirited Away",
  "Howl's Moving Castle",
  "Ponyo",
  "Your Name",
  "Hotarubi no Mori e",
  "We Were There",
  "Nana",
  "Paradise Kiss",
  "Nodame Cantabile",
  "Beck",
  "Kids on the Slope",
  "Blue Period",
  "Kuroko no Basket ",
  "Slam Dunk",
  "Hajime no Ippo",
  "Megalo Box",
  "Ping Pong the Animation",
  "Yuri on Ice",
  "SK8 the Infinity",
  "Ace of Diamond",
  "Major",
  "Touch",
  "Captain Tsubasa",
  "Eyeshield 21",
  "All Out!!",
  "Chihayafuru",
  "Hanebado!",
  "Baby Steps",
  "Free!",
  "Yankee-kun to Megane-chan",
  "GTO",
  "Great Teacher Onizuka",
  "Oregairu",
  "Hyouka",
  "Bunny Drop",
  "Amaama to Inazuma",
  "Food Wars!",
  "Bartender",
  "Silver Spoon",
  "Welcome to the N.H.K.",
  "Sayonara Zetsubou Sensei",
  "The Tatami Galaxy",
  "Sakamoto desu ga",
  "Gekkan Shoujo Nozaki-kun",
  "School Rumble",
  "Hayate no Gotoku",
  "To Aru Majutsu no Index",
  "To Aru Kagaku no Railgun",
  "Darker than Black",
  "Kaiba",
  "Kino no Tabi",
  "Haibane Renmei",
  "Texhnolyze",
  "Casshern Sins",
  "Kiznaiver",
  "Re:CREATORS",
  "ID:INVADED",
  "Wonder Egg Priority",
  "Sonny Boy",
  "Odd Taxi",
  "Deca-Dence",
  "Tower of God",
  "The God of High School",
  "Noblesse",
  "Castlevania",
  "Dororo",
  "Vinland Saga",
  "Golden Kamuy",
  "Planetes",
  "Romeo x Juliet",
  "Black Butler",
  "Pandora Hearts",
  "Nabari no Ou",
  "07-Ghost",
  "Fullmetal Alchemist",
  "Ore Monogatari!!",
  "Horimiya",
  "Wotakoi",
  "Net juu no susume",
  "Gamers!",
  "Sono bisque doll",
  "Kanokari",
  "Karakai Jouzu no Takagi-san",
  "Tsuredure Children",
  "Girlish Number",
  "The Comic Artist and His Assistants",
  "Kaminomi",
  "Kiss x Sis",
  "Ishuzoku Reviewers",
  "Shinmai Maou no Testament",
  "Freezing",
  "Spirit Chronicles",
  "World's End Harem",
  "Peter Grill",
  "100 Kano",
  "Sewayaki Kitsune no Senko-san",
  "Kobayashi's Dragon Maid",
  "Demi-chan wa Kataritai",
  "Blend S",
  "Gabriel DropOut",
  "Asobi Asobase",
  "Himouto! Umaru-chan",
  "Gochuumon wa Usagi Desu ka?",
  "Girls und Panzer",
  "Strike Witches",
  "Upotte!!",
  "Junjou Romantica",
  "Sekaiichi Hatsukoi",
  "Haifuri",
  "Akatsuki no Yona",
  "Junko no Saiunkoku",
  "Otome Youkai Zakuro",
  "Oda Nobuna no Yabou",
  "Sengoku Collection",
  "Hyakko",
  "Maria-sama ga Miteru ",
  "Strawberry Panic!",
  "Simoun",
  "Revolutionary Girl Utena",
  "Please Save My Earth",
  "Onegai Teacher",
  "Mai-Otome",
  "Mai-HiME",
  "Lost Universe",
  "Sister Princess",
  "Hand Maid May",
  "Mahoromatic",
  "Kimagure Orange Road",
  "DNA²",
  "Outlaw Star",
  "Samurai X",
  "Magi",
  "Boruto",
  "Naruto Shippuden",
  "Dragon Ball Z",
  "Dragon Ball Super",
  "FLCL",
  "Excel Saga",
  "Space Brothers",
  "Grimgar",
  "DanMachi"
];